services:
    sonata.admin.website:
        class: Amtt\AppBundle\Admin\WebsiteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Sites Club Auto" }
        arguments:
            - ~
            - Amtt\AppBundle\Entity\Website
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]

    sonata.admin.page:
        class: Amtt\AppBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Gérer les pages" }
        arguments:
            - ~
            - Amtt\AppBundle\Entity\Page
            - AmttAppBundle:PageCRUD
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]

    sonata.admin.page_block:
        class: Amtt\AppBundle\Admin\BlockAdmin
        tags:
            - { name: sonata.admin, manager_type: orm }
        arguments:
            - ~
            - Amtt\AppBundle\Entity\Block
            - AmttAppBundle:BlockCRUD
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setTemplate, [edit, AmttAppBundle:Admin/Block:edit.html.twig]]