club_auto_home:
    path: /
    defaults: { _controller: AmttAppBundle:Home:index }

occasion_home:
    path: /voitures-occasion-{slug}
    defaults: { _controller: AmttAppBundle:Home:index }

occasion_home:
    path: /voitures-occasion-{slug}
    defaults: { _controller: AmttAppBundle:Home:index }