parameters:
#    amtt_api.example.class: Amtt\ApiBundle\Example

services:
#    amtt_api.example:
#        class: %amtt_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
